-- 0016_page_document.sql
-- Full public-page content as ONE editable JSON document per program.
-- Shape = the object src/js/worlds.js already renders (eventName, dates, tagline,
-- logo, sections[], cost, bring[], contacts[], register[], verse). The admin "Web
-- Page Details" tab edits this document; PUT /api/admin/page-document publishes it;
-- the public site (once wired) reads it from GET /api/public/page-document, falling
-- back to the baked-in static content if the fetch fails. Seeded here with the
-- exact current content so nothing is lost. Non-ASCII is \u-escaped (ASCII-safe SQL).

CREATE TABLE IF NOT EXISTS page_document (
  program    TEXT PRIMARY KEY CHECK(program IN ('mens','women')),
  doc        TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

INSERT OR REPLACE INTO page_document (program, doc, updated_at)
VALUES ('mens', '{"eventName":"NWKS Men\u2019s Encounter","dates":"August 6 \u2013 8, 2026","logo":"men-logo-300x300-1.jpg","tagline":"It is for freedom that Christ has set us free.","sections":[{"id":"what-is","title":"What is Men\u2019s Encounter?","blocks":["Connect with other guys and take an honest look at your walk with God. Over the weekend, you''ll examine 14 areas of your life through worship, testimonies, teaching, and ministry."]},{"id":"pre-encounter","title":"What is Pre-Encounter?","blocks":["Teachings and testimonies to prepare you for the weekend, held at your church before you leave."]},{"id":"weekend","title":"The Weekend","blocks":["Leave Thursday evening from a launch-point church \u2014 Norton, Hays, Colby, Gove, Hoxie, or Plainville. Arrival is 4:00\u20136:30 pm; each location departs at its own time, so park at the church.","Return Saturday, 4:00\u20135:00 pm.","Destination: Lakeview Christian Camp, Stockton, KS (Webster Lake). Ride together \u2014 don''t take your own vehicle."]}],"cost":"$125 \u2014 covers transportation, lodging, materials, and meals. Scholarships are available on request. Checks payable to Norton Christian Church, 208 N. Kansas Ave, Norton, KS 67654.","bring":["Sleeping bag","Pillow(s)","Toiletries","Towel","Flashlight","A Bible (don''t pack it \u2014 you''ll need it Thursday)","Clothing for Friday & Saturday"],"contacts":[{"name":"Norton \u2014 Lucas Melvin","phone":"785-202-0302"},{"name":"Hays \u2014 Len Melvin","phone":"785-650-3366"},{"name":"Colby \u2014 Jake Haines","phone":"785-443-2438"},{"name":"Hoxie \u2014 Seth Slaughbaugh","phone":"785-627-6092"},{"name":"Gove \u2014 Von Tuttle","phone":"785-673-9534"},{"name":"Sterling \u2014 Nick Sowers","phone":"620-680-0166"}],"register":[{"label":"Register as an Attendee","href":"https://docs.google.com/forms/d/e/1FAIpQLSdZoPlopEZyHpBLl4EnXZuiB8X6vCDAR5v7Nw726rgtFQiNQw/viewform"}],"verse":"\"It is for freedom that Christ has set us free.\" \u2014 Galatians 5:1"}', '2026-07-27T00:00:00.000Z');

INSERT OR REPLACE INTO page_document (program, doc, updated_at)
VALUES ('women', '{"eventName":"NWKS Women\u2019s Encounter","dates":"July 17 \u2013 19, 2026","logo":"source-womens-logo-1024x1024.jpg","tagline":"It is for freedom that Christ has set us free.","sections":[{"id":"registration-timeline","title":"Registration Timeline","blocks":["Attendee registration opens May 17, 2026 at 9:00 am. The $125 fee is due July 17.","Server registration opens May 17 at 9:00 am \u2014 and is currently FULL. The $125 fee is due at the mandatory Server Training, June 14 at 4:00 pm, Hays Celebration Community Church."]},{"id":"what-is","title":"What is Women\u2019s Encounter?","blocks":["A weekend to encounter Christ in ways that are new, or long since felt. Through teaching, testimonies, and worship, you are free to be as social or as quiet as you wish \u2014 no comfort zones forced.","This isn''t a typical retreat. It''s an individual, personal experience between you and God."]},{"id":"weekend","title":"The Weekend","blocks":["Leave Friday evening from a launch-point church \u2014 Colby, Gove, Hays, Hoxie, Norton, Plainville, Sterling, or WaKeeney. Registration and launch is 4:00\u20135:30 pm (Sterling meets earlier).","Return Sunday, 4:00\u20135:00 pm.","Destination: Lakeview Christian Camp, Stockton, KS."]}],"cost":"$125 (write \"Women''s Encounter\" in the memo) \u2014 covers transportation, lodging, materials, and meals. Checks payable to Norton Christian Church.","bring":["Bedding for a twin bed, or a sleeping bag","Pillow(s)","Toiletries","Bath towel & washcloth","Flashlight","Casual clothes for Saturday & Sunday, plus a jacket","A Bible and a journal/notebook (don''t pack \u2014 you''ll need them Friday evening)"],"contacts":[{"name":"Registration questions","email":"nwkswomensencounter@gmail.com"},{"name":"Angela Melvin","phone":"785-871-0848","email":"angelarmelvin@gmail.com"},{"name":"Danielle Markley","phone":"785-639-2896","email":"danielle@haysacademy.com"}],"register":[{"label":"Register","href":"https://forms.gle/KMz3phZ3fNg2nNx57"},{"label":"Email Registration Questions","href":"mailto:nwkswomensencounter@gmail.com"}],"verse":"\"It is for freedom that Christ has set us free.\" \u2014 Galatians 5:1"}', '2026-07-27T00:00:00.000Z');
